### ISSUE TITLE
Any hope of having pretrained weights ?

### ISSUE THREAD

**Issue by ShihuaiXu** [YeongHyeon/ResNeSt-TF2#2]
thank you in advance

**Comment by YeongHyeon** [comment]
My answer is the same as in your previous issue.

https://github.com/YeongHyeon/ResNeSt-TF2/issues/1#issuecomment-711456901

**Comment by YeongHyeon** [comment]
Hi,
Now the pre-trained ResNeSt is provided in this repository, via TensorFlow lite. 
https://github.com/YeongHyeon/ResNeSt-TF2/blob/master/misc/model.tflite

Thank you for your interest.
:)
